Add feature location_processing
pavp1/java-explore-with-me pull request #5
Opened 2023-10-19 10:04 UTC by pavp1

2023-10-20 06:20 UTC, alexache requested changes

2023-10-20 06:20 UTC, alexache commented on main/src/main/java/ru/practicum/explorewithme/main/controller/AdminLocationController.java
> +@Validated
Это лишние - валидаций, кроме через @Valid нет

2023-10-20 06:20 UTC, alexache commented on main/src/main/java/ru/practicum/explorewithme/main/controller/LocationController.java
> +@Validated
Но нет валидаций?

2023-10-20 06:20 UTC, alexache commented on main/src/main/resources/schema.sql
> +    declare
Ох как мощно, на обычном запросе к базе точно не получится?

2023-10-20 06:20 UTC, alexache commented on postman/feature.json
> +			},
Чуть бы побольше кейсов - несколько событий возвращаться, пограничные ситуации, где событие почти на границе радиуса

2023-10-20 09:06 UTC, pavp1 commented on main/src/main/resources/schema.sql
> +    declare
Можно использовате приблизительнрый запрос на основе формула гаверсинусов, но на моём примере у неё погрешность в три километра из-за использования в расчётах идеальной сферы, как формы земли.
```
SELECT SQRT(POW(69.1 * (55.6014233::float - 58.375::float), 2) +
            POW(69.1 * (38.417778::float - 35.6614418::float) * COS(55.6014233::float / 57.3), 2)
       ) * 1.609343502101154 as result;
```
       Выдаёт результат: 353.7327237431967
       Против 350.4810377014076 у
`      select distance(55.6014233, 35.6614418, 58.375, 38.417778);`

Так как функцию distance нам рекомендовали в техническом задании с указанной реализацией - использовал её.

2023-10-20 10:29 UTC, pavp1 commented on postman/feature.json
> +			},
Добавил создание второго события и два случая пограничного поиска от центральной точки между этими событиями. Первый - когда радиус поиска не захватывает оба события. Второй, когда минимальное увеличения радиуса начинает захватывать оба события.

2023-10-21 16:56 UTC, alexache approved these changes

2023-10-23 12:57 UTC, merged